### ISSUE TITLE
Input errors not show

### ISSUE THREAD

**Issue by jojuchatru1993** [hail812/yii2-adminlte3#10]
Hi, first thanks for you respository.

I would like to know why the errors in the entries are not seen in AdminLTE3, I have an example in AdminLTE2 and if they are.

![adminlte2](https://user-images.githubusercontent.com/5804657/115802649-ea8ceb80-a3a4-11eb-847f-94988eb72083.png)
![adminlte3](https://user-images.githubusercontent.com/5804657/115802651-eb258200-a3a4-11eb-9796-36690c470a64.png)

**Comment by muyuym** [comment]
have you check the rules() of model

**Comment by muyuym** [comment]
![1811619141904_ pic](https://user-images.githubusercontent.com/3158261/115805495-ae46a300-a417-11eb-826b-299b94e734f6.jpg)

**Comment by jojuchatru1993** [comment]
Yes, in my example I see the error but not with the color red

![rules](https://user-images.githubusercontent.com/5804657/115806194-ea441e80-a3ab-11eb-8162-028a386c3187.png)
![adminlte3](https://user-images.githubusercontent.com/5804657/115806102-c41e7e80-a3ab-11eb-980b-0e10cf6c07ae.png)

**Comment by jojuchatru1993** [comment]
I'm sorry.
The error was in my _form.php.
It is required to use use yii\bootstrap4\ActiveForm;

**Comment by muyuym** [comment]
![1821619142872_ pic_hd](https://user-images.githubusercontent.com/3158261/115806756-ef3fb700-a419-11eb-8a83-378f171c09c9.jpg)
