### ISSUE TITLE
compatible with yii2-giiant?

### ISSUE THREAD

**Issue by masiorama** [hail812/yii2-adminlte3#11]
Hello, thank your for your module!

For my project I am using https://github.com/schmunk42/yii2-giiant, working mainly via shell.

Is your module compatible with it, in your opinion?

Thanks in advance.

**Comment by muyuym** [comment]
yii2-giiant has own ui, and yii2-adminlte3 uses adminlte3

**Comment by masiorama** [comment]
So I cannot leverage on your generator file (prepared for  yii gii) and port it as a giiant customer generator? Is this correct?
Thanks!

**Comment by muyuym** [comment]
Can giiant config template ?

**Comment by masiorama** [comment]
Still investigating... from this https://github.com/schmunk42/yii2-giiant/issues/116 I think it could be possibile, but I'm not so skilled about generators  to judge myself. What do you think? 
Thanks!
