### ISSUE TITLE
Setup control sidebar and some UI diferences

### ISSUE THREAD

**Issue by leocharrua** [hail812/yii2-adminlte3#13]
Hello. Thanks @hail812 for your work, it's excelent!!!

1) I'm starting from the yii2 basic boirlerplate. It's that the right way?

2) How to show the AdminLTE control sidebar (for change colors, etc.). I suppose is a plugin, isn't it?

3) I have some UI differences with your screenshots. For example, I don't get the user profile in the header and there's a new search full length control. Is a new version?

Thanks

"hail812/yii2-adminlte3": "~1.1"

name     : hail812/yii2-adminlte3
descrip. : adminlte3 for yii2
keywords : AdminLTE, extension, yii2
versions : * v1.1.3

![adminlte1](https://user-images.githubusercontent.com/1721923/119229563-0512cb80-baef-11eb-9c58-b2f15cfc6ea2.jpg)
![adminlte2](https://user-images.githubusercontent.com/1721923/119229565-0643f880-baef-11eb-9bb8-6333e46b584c.jpg)

**Comment by muyuym** [comment]
this screenshots is new, and screenshots in readme is old. I will update screenshots in the future.

the user profile is none in adminlte v3, if you need it，you can see
![image](https://user-images.githubusercontent.com/3158261/119283612-27802280-bc70-11eb-8e27-ce052e66b126.png)
[delete user profile in header in this commit](https://github.com/hail812/yii2-adminlte3/commit/9eedcfe7d392482f55b388271965a623fbd7f717) navbar.php

the control sidebar，you can see adminlte/dist/js/demo.js
