### ISSUE TITLE
 Incompatible interface

### ISSUE THREAD

**Issue by MinatoFanboy** [hail812/yii2-adminlte3#15]
I found some crash in sidebar when using kartik\grid\GridView. What can I do[
![cash](https://user-images.githubusercontent.com/78007834/132861092-114a269a-880c-457f-b13b-ab93dd607409.png)
](url)

**Comment by neoacevedo** [comment]
I think because kartik-v grid loads a different version of bootstrap. I saw the same and I had to use the default grid widget.

**Comment by zzbajie** [comment]
params.php
`{
  return [
      'adminEmail' => 'admin@example.com',
      'PAGESIZEMAX'=>10,
      'bsVersion' => '4.x', //kartik-v
  ];
}`
