### ISSUE TITLE
Alert displayed without being invoked

### ISSUE THREAD

**Issue by cahyasatya77** [hail812/yii2-adminlte3#16]
Adding `<?= \hail812\adminlte\widgets\Alert::widget(); ?>` into the content layout, the alert widget is displayed in each page without actually to have invoked to setFlash session method, while the Yii2 alert widget only is showed when a setFlash message is invoked.

**Comment by dpchami** [comment]
You need to create your own custom Widget Alert to incorporate your requirements. That one is not controlled by default session configuration
