### ISSUE TITLE
Login view

### ISSUE THREAD

**Issue by jashirouprotips** [hail812/yii2-adminlte3#3]
Hi,

I have an issue with the login view.

My boss want the classic login form, where the form is alone and the others elements (sidebar and navbar) are not included in the "site/login" route.

How can I change this:
![image](https://user-images.githubusercontent.com/29470002/84094818-e2a9a000-a9ba-11ea-9b79-e2a7a26667d3.png)

To this?:
![image](https://user-images.githubusercontent.com/29470002/84095077-8e52f000-a9bb-11ea-95ec-68f565a093e3.png)

I will really very thankfully.

Thanks in advance.

**Comment by muyuym** [comment]
Hi @jashirouprotips, 

You should set  the layout to 'main-login' or false.
```
    public function actionLogin()
    {
        // $this->layout = 'main-login';
        $this->layout = false;

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
```

**Comment by jashirouprotips** [comment]
> Hi @jashirouprotips,
> 
> You should set the layout to 'main-login' or false.
> 
> ```
>     public function actionLogin()
>     {
>         // $this->layout = 'main-login';
>         $this->layout = false;
> 
>         if (!Yii::$app->user->isGuest) {
>             return $this->goHome();
>         }
> 
>         $model = new LoginForm();
>         if ($model->load(Yii::$app->request->post()) && $model->login()) {
>             return $this->goBack();
>         } else {
>             $model->password = '';
> 
>             return $this->render('login', [
>                 'model' => $model,
>             ]);
>         }
>     }
> ```

Excellent...you saved my day...

Thanks again dude...well done with this plugin...
