### ISSUE TITLE
I can't get gii to work.  Goes to #403 error.

### ISSUE THREAD

**Issue by hellenas** [hail812/yii2-adminlte3#5]
Can you help please?

Thanks.

**Comment by muyuym** [comment]
https://stackoverflow.com/questions/26315808/yii2-gii-forbidden-code-403-you-are-not-allowed-to-access-this-page

**Comment by hellenas** [comment]
Thank you for your reply.  I try to research first before I bother someone - I will try over 100 links before I contact someone.  And, that link was one of my first.  But, I happily found the issue.  It was another extension that caused the gii not to work.  

I kept wondering why I was consistently "forbidden" on it, so I figured it may be another access extension that I used.  Sure enough, once I removed it, the Gii worked.

But, I want to say, thank you so much for responding.  I really appreciate it.

Have a great day!

P.S.  I really love your work.
