### ISSUE TITLE
Css and sidebar crash 

### ISSUE THREAD

**Issue by fauzannoorazhar** [hail812/yii2-adminlte3#7]
I found some crash in sidebar when using extension select2 kartik 

![image](https://user-images.githubusercontent.com/28283735/111507129-e86bb780-877c-11eb-952a-6f1bd1d8290b.png)
screen normaly

![image](https://user-images.githubusercontent.com/28283735/111506858-a5114900-877c-11eb-91b8-e0ad257a1108.png)
when the screen render select2 in view

![image](https://user-images.githubusercontent.com/28283735/111507470-44ced700-877d-11eb-887a-772175796403.png)
this is my required extension, use kartik-v/yii2-widget-select2 from dev-master

**Comment by muyuym** [comment]
### select2 should be load before adminlte

<img width="711" alt="WeChat9fd30b1f7bc31883860cd0117115006c" src="https://user-images.githubusercontent.com/3158261/111563637-46c38500-87d3-11eb-9efc-47b2227b127e.png">

<img width="792" alt="WeChat092349362440b1b82e273b7cb12504ba" src="https://user-images.githubusercontent.com/3158261/111563717-73779c80-87d3-11eb-9e64-858286b0ef63.png">
