### ISSUE TITLE
Tabs widget causes decreasing font-size

### ISSUE THREAD

**Issue by BesjaSoft** [hail812/yii2-adminlte3#9]
Hi,
In a view generated by GII the fontsize turns out to be 16px, which is fine.  The view is generated by a Detailview.

When I add a Tab-widget to the view, the fontsize decreases into 10px. Not only for the view but for the entire page. 

Questions: do you recognise the problem and is there a simple solution other than not using the tab-widget. If needed I can provide the source code of the view and screenshots of the application.

**Comment by muyuym** [comment]
what causes

**Comment by BesjaSoft** [comment]
Hi, sorry to have bothered you... By fiddling around a bit I now use the yii\bootstrap4\Tabs and this works fine.
Issue can be closed
